/* Pruebas para GITHUB a 09/12/2016
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ribanez
 */
public class Articulos extends javax.swing.JFrame {

static public ResultSet r;
static public ResultSet r2;
static public ResultSet r3;
static public Connection conexion;

char esNuevo = ' ';

    public Articulos() throws SQLException {
        initComponents();
     
        String url = "jdbc:mysql://localhost:3306/bases";
        String user = "root";
        String pass = "";
        conexion = DriverManager.getConnection(url,user, pass);
        
    // Prepara la conexion de la tabla articulos
        Statement s = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select articulos.*, fabricantes.NOMBRE from articulos left join fabricantes on FABRICANTE = COD_FABRICANTE";
        r = s.executeQuery(query);
   
    // Saca el primer registro de articulos
        r.first();
            primerRegistro();
     
    //Desactivar campos
        cod_articulo.setEditable(false);
        articulo.setEditable(false);
        fabricante.setEditable(false);
        nombre.setEditable(false);
        peso.setEditable(false);
        categoria.setEditable(false);
        precio_venta.setEditable(false);
        precio_coste.setEditable(false);
        existencias.setEditable(false);        
    
        this.BotonAceptar.setVisible(false);
        this.BotonCancelar.setVisible(false);
       
        // Genera el combo del nombre de fabricante
          comboFabricante();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTITULO = new javax.swing.JLabel();
        LabelCOD_ARTICULO = new javax.swing.JLabel();
        LabelARTICULO = new javax.swing.JLabel();
        LabelFABRICANTE = new javax.swing.JLabel();
        LabelPESO = new javax.swing.JLabel();
        LabelCATEGORIA = new javax.swing.JLabel();
        LabelPRECIO_VENTA = new javax.swing.JLabel();
        LabelPRECIO_COSTE = new javax.swing.JLabel();
        LabelEXISTENCIAS = new javax.swing.JLabel();
        cod_articulo = new javax.swing.JTextField();
        articulo = new javax.swing.JTextField();
        fabricante = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        precio_venta = new javax.swing.JTextField();
        precio_coste = new javax.swing.JTextField();
        existencias = new javax.swing.JTextField();
        BotonPrimero = new javax.swing.JButton();
        BotonAnterior = new javax.swing.JButton();
        BotonSiguiente = new javax.swing.JButton();
        BotonUltimo = new javax.swing.JButton();
        BotonNuevo = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonSuprimir = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonAceptar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        ComboNombre = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLICACION : EJERCICIO2 (BASES)");

        LabelTITULO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTITULO.setText("MANTENIMIENTO DE ARTICULOS");

        LabelCOD_ARTICULO.setText("CODIGO");

        LabelARTICULO.setText("ARTICULO");

        LabelFABRICANTE.setText("FABRICANTE");

        LabelPESO.setText("PESO");

        LabelCATEGORIA.setText("CATEGORIA");

        LabelPRECIO_VENTA.setText("PRECIO VENTA");

        LabelPRECIO_COSTE.setText("PRECIO COSTE");

        LabelEXISTENCIAS.setText("EXISTENCIAS");

        cod_articulo.setEditable(false);
        cod_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_articuloActionPerformed(evt);
            }
        });

        fabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fabricanteActionPerformed(evt);
            }
        });

        precio_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_ventaActionPerformed(evt);
            }
        });

        precio_coste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_costeActionPerformed(evt);
            }
        });

        existencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existenciasActionPerformed(evt);
            }
        });

        BotonPrimero.setText("Primero");
        BotonPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrimeroActionPerformed(evt);
            }
        });

        BotonAnterior.setText("Anterior");
        BotonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnteriorActionPerformed(evt);
            }
        });

        BotonSiguiente.setText("Siguiente");
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });

        BotonUltimo.setText("Ultimo");
        BotonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUltimoActionPerformed(evt);
            }
        });

        BotonNuevo.setForeground(new java.awt.Color(0, 153, 204));
        BotonNuevo.setText("Nuevo");
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });

        BotonModificar.setForeground(new java.awt.Color(255, 153, 51));
        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        BotonSuprimir.setForeground(new java.awt.Color(255, 0, 51));
        BotonSuprimir.setText("Suprimir");
        BotonSuprimir.setToolTipText("");
        BotonSuprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSuprimirActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonAceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonAceptar.setForeground(new java.awt.Color(0, 204, 102));
        BotonAceptar.setText("√");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        BotonCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonCancelar.setForeground(new java.awt.Color(255, 0, 0));
        BotonCancelar.setText("X");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        ComboNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(LabelTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BotonPrimero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonAnterior)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonSiguiente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonUltimo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(BotonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonSuprimir)))
                                .addGap(47, 47, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonCancelar)
                                    .addComponent(BotonAceptar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelPRECIO_COSTE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precio_coste, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelFABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelPESO, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelPRECIO_VENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelCOD_ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cod_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LabelEXISTENCIAS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(existencias, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalir))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BotonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCOD_ARTICULO)
                    .addComponent(cod_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelARTICULO)
                    .addComponent(articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFABRICANTE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPESO)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCATEGORIA)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPRECIO_VENTA)
                    .addComponent(precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPRECIO_COSTE)
                    .addComponent(precio_coste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEXISTENCIAS)
                    .addComponent(existencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonPrimero)
                    .addComponent(BotonAnterior)
                    .addComponent(BotonSiguiente)
                    .addComponent(BotonUltimo)
                    .addComponent(BotonAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevo)
                    .addComponent(BotonModificar)
                    .addComponent(BotonCancelar)
                    .addComponent(BotonSuprimir))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fabricanteActionPerformed

    private void precio_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_ventaActionPerformed

    private void cod_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_articuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_articuloActionPerformed

    private void BotonPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrimeroActionPerformed
    try {
        r.first();
        cod_articulo.setText(r.getString("COD_ARTICULO"));
        articulo.setText(r.getString("ARTICULO"));
        fabricante.setText(r.getString("FABRICANTE"));
        nombre.setText(r.getString("NOMBRE"));
        peso.setText(r.getString("PESO"));
        categoria.setText(r.getString("CATEGORIA"));
        precio_venta.setText(r.getString("PRECIO_VENTA"));
        precio_coste.setText(r.getString("PRECIO_COSTE"));
        existencias.setText(r.getString("EXISTENCIAS"));        
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BotonPrimeroActionPerformed

    private void BotonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUltimoActionPerformed
    try {
        r.last();
        cod_articulo.setText(r.getString("COD_ARTICULO"));
        articulo.setText(r.getString("ARTICULO"));
        fabricante.setText(r.getString("FABRICANTE"));
        nombre.setText(r.getString("NOMBRE"));
        peso.setText(r.getString("PESO"));
        categoria.setText(r.getString("CATEGORIA"));
        precio_venta.setText(r.getString("PRECIO_VENTA"));
        precio_coste.setText(r.getString("PRECIO_COSTE"));
        existencias.setText(r.getString("EXISTENCIAS"));
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BotonUltimoActionPerformed

    private void BotonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnteriorActionPerformed
    try {
        if (r.previous()){
            cod_articulo.setText(r.getString("COD_ARTICULO"));
            articulo.setText(r.getString("ARTICULO"));
            fabricante.setText(r.getString("FABRICANTE"));
            nombre.setText(r.getString("NOMBRE"));
            peso.setText(r.getString("PESO"));
            categoria.setText(r.getString("CATEGORIA"));
            precio_venta.setText(r.getString("PRECIO_VENTA"));
            precio_coste.setText(r.getString("PRECIO_COSTE"));
            existencias.setText(r.getString("EXISTENCIAS"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }        
    }//GEN-LAST:event_BotonAnteriorActionPerformed

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
    try {
        if (r.next()){
            cod_articulo.setText(r.getString("COD_ARTICULO"));
            articulo.setText(r.getString("ARTICULO"));
            fabricante.setText(r.getString("FABRICANTE"));
            nombre.setText(r.getString("NOMBRE"));
            peso.setText(r.getString("PESO"));
            categoria.setText(r.getString("CATEGORIA"));
            precio_venta.setText(r.getString("PRECIO_VENTA"));
            precio_coste.setText(r.getString("PRECIO_COSTE"));
            existencias.setText(r.getString("EXISTENCIAS"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        // instrucciones para insertar nuevo registro
        // hay que ocultar botones y poner nuevos ACEPTAR y CANCELAR
        this.BotonPrimero.setVisible(false);
        this.BotonAnterior.setVisible(false);
        this.BotonSiguiente.setVisible(false);
        this.BotonUltimo.setVisible(false);
        this.BotonNuevo.setVisible(false);
        this.BotonModificar.setVisible(false);
        this.BotonSuprimir.setVisible(false);
        
        this.BotonAceptar.setVisible(true);
        this.BotonCancelar.setVisible(true);
        
        //this.BotonAceptar.setEnabled(true);
        //this.BotonAceptar.setEnabled(true);
       
        // Limpiar la pantalla
        cod_articulo.setText(""); 
        articulo.setText(""); 
        fabricante.setText("");
        nombre.setText("");
        peso.setText("");
        categoria.setText("");
        precio_venta.setText("");
        precio_coste.setText("");
        existencias.setText("");
        
        //Activar campos
            cod_articulo.setEditable(true);
            articulo.setEditable(true);
            fabricante.setEditable(true);
            nombre.setEditable(true);
            peso.setEditable(true);
            categoria.setEditable(true);
            precio_venta.setEditable(true);
            precio_coste.setEditable(true);
            existencias.setEditable(true);   
            
        //Activar el foco
        cod_articulo.requestFocus();
        
        // Variable control boton Aceptar
        esNuevo = 'N';    
    }//GEN-LAST:event_BotonNuevoActionPerformed

    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
        // hay que ocultar botones y poner nuevos ACEPTAR y CANCELAR
        this.BotonPrimero.setVisible(false);
        this.BotonAnterior.setVisible(false);
        this.BotonSiguiente.setVisible(false);
        this.BotonUltimo.setVisible(false);
        this.BotonNuevo.setVisible(false);
        this.BotonModificar.setVisible(false);
        this.BotonSuprimir.setVisible(false);
            
        this.BotonAceptar.setVisible(true);
        this.BotonCancelar.setVisible(true);
        
        //Activar campos
            cod_articulo.setEditable(false);
            articulo.setEditable(true);
            fabricante.setEditable(true);
            nombre.setEditable(true);
            peso.setEditable(true);
            categoria.setEditable(true);
            precio_venta.setEditable(true);
            precio_coste.setEditable(true);
            existencias.setEditable(true);  
            
        //Activar el foco
            articulo.requestFocus();
        
        // Variable control boton Modificar
            esNuevo = 'M';  
    }//GEN-LAST:event_BotonModificarActionPerformed

    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
    try {
        String VCod_articulo, vArticulo, vFabricante, vPeso, vCategoria, vPrecioventa, vPreciocoste, vExistencias;
        VCod_articulo = cod_articulo.getText();
        vArticulo = articulo.getText();
        vFabricante = fabricante.getText();
        vPeso = peso.getText();
        vCategoria = categoria.getText();
        vPrecioventa = precio_venta.getText();
        vPreciocoste = precio_coste.getText();
        vExistencias = existencias.getText();
        // conectar la base de datos
        String url = "jdbc:mysql://localhost:3306/bases";
        String user = "root";
        String pass = "";
        Connection connection = DriverManager.getConnection(url, user, pass);
        Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
      
        // Generar la instruccion de borrar
        if (esNuevo == 'B'){
        String BorraRegistro = "DELETE FROM articulos WHERE COD_ARTICULO='" + VCod_articulo + "'";
        int controlBorra = s.executeUpdate(BorraRegistro);
        // r.refreshRow(); 
        }
        // Generar la instruccion de actualizar        
        if (esNuevo == 'M'){
        String ActualizaRegistro = "update articulos set ARTICULO='" + vArticulo + "', FABRICANTE='" + vFabricante + "', PESO='" + vPeso + "', CATEGORIA='" + vCategoria + "', PRECIO_VENTA='" + vPrecioventa + "', PRECIO_COSTE='" + vPreciocoste + "', EXISTENCIAS='" + vExistencias + "' WHERE COD_ARTICULO='" + VCod_articulo +"'";
        int controlActualiza = s.executeUpdate(ActualizaRegistro);
        r.refreshRow();
        }
        // Generar la instruccion de Nuevo Registro
        if (esNuevo == 'N'){
        String NuevoRegistro = "insert into articulos values ('" + VCod_articulo + "','" + vArticulo + "','" + vFabricante + "','" + vPeso + "','" + vCategoria + "','" + vPrecioventa + "','" + vPreciocoste + "','" + vExistencias + "')";
        int controlNuevo = s.executeUpdate(NuevoRegistro);
        // r.refreshRow(); 
        }
        // Volver a refrescar la base de datos
        if (esNuevo != 'M'){
        String query = "select articulos.*, fabricantes.NOMBRE from articulos left join fabricantes on FABRICANTE = COD_FABRICANTE";   
            r = s.executeQuery(query);
            r.first();
            cod_articulo.setText(r.getString("COD_ARTICULO"));
            articulo.setText(r.getString("ARTICULO"));
            fabricante.setText(r.getString("FABRICANTE"));
            nombre.setText(r.getString("NOMBRE"));
            peso.setText(r.getString("PESO"));
            categoria.setText(r.getString("CATEGORIA"));
            precio_venta.setText(r.getString("PRECIO_VENTA"));
            precio_coste.setText(r.getString("PRECIO_COSTE"));
            existencias.setText(r.getString("EXISTENCIAS"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }
        // Volver activar los botones
            this.BotonPrimero.setVisible(true);
            this.BotonAnterior.setVisible(true);
            this.BotonSiguiente.setVisible(true);
            this.BotonUltimo.setVisible(true);
            this.BotonNuevo.setVisible(true);
            this.BotonModificar.setVisible(true);
            this.BotonSuprimir.setVisible(true);
            
            this.BotonAceptar.setVisible(false);
            this.BotonCancelar.setVisible(false);
 
        //Activar el foco
            cod_articulo.setEditable(false);
            articulo.setEditable(false);
            fabricante.setEditable(false);
            nombre.setEditable(false);
            peso.setEditable(false);
            categoria.setEditable(false);
            precio_venta.setEditable(false);
            precio_coste.setEditable(false);
            existencias.setEditable(false);
            
        // Variable control boton
            esNuevo = ' ';           
    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        // Volver activar los botones
            this.BotonPrimero.setVisible(true);
            this.BotonAnterior.setVisible(true);
            this.BotonSiguiente.setVisible(true);
            this.BotonUltimo.setVisible(true);
            this.BotonNuevo.setVisible(true);
            this.BotonModificar.setVisible(true);
            this.BotonSuprimir.setVisible(true);
            
            this.BotonAceptar.setVisible(false);
            this.BotonCancelar.setVisible(false);
        
        try {
            r.first();
            cod_articulo.setText(r.getString("COD_ARTICULO"));
            articulo.setText(r.getString("ARTICULO"));
            fabricante.setText(r.getString("FABRICANTE"));
            nombre.setText(r.getString("NOMBRE"));
            peso.setText(r.getString("PESO"));
            categoria.setText(r.getString("CATEGORIA"));
            precio_venta.setText(r.getString("PRECIO_VENTA"));
            precio_coste.setText(r.getString("PRECIO_COSTE"));
            existencias.setText(r.getString("EXISTENCIAS"));
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Activar campos
            cod_articulo.setEditable(false);
            articulo.setEditable(false);
            fabricante.setEditable(false);
            nombre.setEditable(false);
            peso.setEditable(false);
            categoria.setEditable(false);
            precio_venta.setEditable(false);
            precio_coste.setEditable(false);
            existencias.setEditable(false);
            
        // Variable control boton
            esNuevo = ' '; 
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonSuprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSuprimirActionPerformed
            // hay que ocultar botones y poner nuevos ACEPTAR y CANCELAR
            this.BotonPrimero.setVisible(false);
            this.BotonAnterior.setVisible(false);
            this.BotonSiguiente.setVisible(false);
            this.BotonUltimo.setVisible(false);
            this.BotonNuevo.setVisible(false);
            this.BotonModificar.setVisible(false);
            this.BotonSuprimir.setVisible(false);

            this.BotonAceptar.setVisible(true);
            this.BotonCancelar.setVisible(true);
        
        //Activar campos
            cod_articulo.setEditable(false);
            articulo.setEditable(false);
            fabricante.setEditable(false);
            nombre.setEditable(false);
            peso.setEditable(false);
            categoria.setEditable(false);
            precio_venta.setEditable(false);
            precio_coste.setEditable(false);
            existencias.setEditable(false);
             
        // Variable control boton Suprimir
            esNuevo = 'B';
    }//GEN-LAST:event_BotonSuprimirActionPerformed

    private void precio_costeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_costeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_costeActionPerformed

    private void existenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existenciasActionPerformed

    private void ComboNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNombreActionPerformed

        //Recuperar el nombre y el codigo para presentarlo en pantalla
  
    }//GEN-LAST:event_ComboNombreActionPerformed

// METODO PARA SACAR EL PRIMER REGISTRO#########################################
    public void primerRegistro(){
        try {
            cod_articulo.setText(r.getString("COD_ARTICULO"));
            articulo.setText(r.getString("ARTICULO"));
            fabricante.setText(r.getString("FABRICANTE"));   //Codigo Fabricante
            nombre.setText(r.getString("NOMBRE"));           //Nombre Fabricante
            peso.setText(r.getString("PESO"));
            categoria.setText(r.getString("CATEGORIA"));
            precio_venta.setText(r.getString("PRECIO_VENTA"));
            precio_coste.setText(r.getString("PRECIO_COSTE"));
            existencias.setText(r.getString("EXISTENCIAS"));
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
// METODO PARA GENERAR EL COMBO PARA EL NOMBRE DEL FABRICANTE###################
    public void comboFabricante(){
        try{
            Statement s2 = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query2 = "Select * from fabricantes";
            r2 = s2.executeQuery(query2);
            DefaultComboBoxModel value2 = new DefaultComboBoxModel();
            while (r2.next()) {
                value2.addElement(r2.getString("NOMBRE"));
            }
            ComboNombre.setModel(value2);
            ComboNombre.setSelectedItem(nombreFabricante(r.getInt("NOMBRE")));
            
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
// METODO PARA RECUPERAR EL NOMBRE DEL FABRICANTE ##############################
    public static String nombreFabricante(int codigo){
        String nombre = "";
        try {
            Statement s3 = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query3= "select NOMBRE from fabricantes where COD_FABRICANTE=" + codigo;
            r3 = s3.executeQuery(query3);
            r3.first();
            nombre = r3.getString("NOMBRE");
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }   
    return nombre;
    }
    
// METODO PARA RECUPERAR EL CODIGO DEL FABRICANTE###############################    
    public static int codigoFabricante(String nombre){
        int codigo = 0;
        try {
            Statement s3 = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query3= "select COD_FABRICANTE from fabricantes where NOMBRE=" + nombre;
            r3 = s3.executeQuery(query3);
            r3.first();
            codigo = r3.getInt("COD_FABRICANTE");
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }   
    return codigo;
    }
    
// METODO MAIN##################################################################
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Articulos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonAnterior;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonNuevo;
    private javax.swing.JButton BotonPrimero;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JButton BotonSuprimir;
    private javax.swing.JButton BotonUltimo;
    private javax.swing.JComboBox<String> ComboNombre;
    private javax.swing.JLabel LabelARTICULO;
    private javax.swing.JLabel LabelCATEGORIA;
    private javax.swing.JLabel LabelCOD_ARTICULO;
    private javax.swing.JLabel LabelEXISTENCIAS;
    private javax.swing.JLabel LabelFABRICANTE;
    private javax.swing.JLabel LabelPESO;
    private javax.swing.JLabel LabelPRECIO_COSTE;
    private javax.swing.JLabel LabelPRECIO_VENTA;
    private javax.swing.JLabel LabelTITULO;
    private javax.swing.JTextField articulo;
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField cod_articulo;
    private javax.swing.JTextField existencias;
    private javax.swing.JTextField fabricante;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField precio_coste;
    private javax.swing.JTextField precio_venta;
    // End of variables declaration//GEN-END:variables
}
